spring:
  application:
    name: cadastro-alunos
  profiles:
    active: test

# Configuração do servidor OpenAPI
openapi:
  dev-url: http://localhost:8080
  prod-url: https://rest-api.com

# Configuração do OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# Define o nível de log para o pacote raiz
logger:
  level: INFO

# Define o layout do log
appender:
  console:
    type: Console
    name: STDOUT
    layout:
      type: PatternLayout
      pattern: "%d{yyyy-MM-dd HH:mm:ss} [%t] %-5level %logger{36} - %msg%n"

# Associa o layout ao appender
rootLogger:
  level: INFO
  appenderRefs:
    - console
  appenderRef:
    console:
      ref: STDOUT

# Context path do servidor
# server:
#   servlet:
#     context-path: /spring-boot-rest
