
CREATE TABLE alunos (
    CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(40) NOT NULL,
    ENDERECO VARCHAR(100) NOT NULL,
    TURMA VARCHAR(5) NOT NULL,
    NOTA_1 DECIMAL(3,1) NOT NULL,
    NOTA_2 DECIMAL(3,1) NOT NULL,
    NOTA_3 DECIMAL(3,1) NOT NULL,
    APROVADO VARCHAR(5)
);
