name: CI - Testes Automatizados

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  unit-tests:
    name: Testes Unitários
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Instalar dependências
        run: mvn clean install -DskipTests

      - name: Executar Testes Unitários
        run: mvn test -Dgroups=unitario

  integration-tests:
    name: Testes de Integração
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Instalar dependências
        run: mvn clean install -DskipTests

      - name: Executar Testes de Integração
        run: mvn verify -Dgroups=integracao

  acceptance-tests:
    name: Testes de Aceitação
    runs-on: ubuntu-latest
    needs: integration-tests
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Instalar dependências
        run: mvn clean install -DskipTests

      - name: Executar Testes de Aceitação
        run: mvn verify -Dgroups=aceitacao
